project:
  type: website
  output-dir: docs

website:
  title: "My Website"
  navbar:
    left:
      - text: Home
        file: index.qmd
      - text: Dashboard
        file: dashboard.qmd
      - text: Essay on Shiny Apps
        file: shiny_apps.qmd
      - text: Essay on Shinylive
        file: shiny_live.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

